# Use an official Python runtime as the base image
FROM python:3.6

# Set the working directory in the container
WORKDIR /app

# The EXPOSE instruction indicates the ports on which a container
EXPOSE 5005
# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
COPY requirements.txt /app
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

# Run the command to start the analytics service
CMD ["python", "calculate.py"]