services:
  grades:
    build: ./grades
    command: python app.py
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
    - ./grades:/app
    ports: 
      - "5000:80"
    
  mysql:
    image: mysql:8.0
    volumes:
      - grades-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: grades

volumes:
  grades-mysql-data: