services:
  app:
    build: ./enter_data
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    ports:
      - '3307:3307'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql_db:/docker-entrypoint-initdb.d/:ro
