services:
  auth:
    image: stevenbennett90/3495assignment1-auth:latest
    ports:
      - "5001:5001"
    networks:
      - project1
  app:
    image: stevenbennett90/3495assignment1-entry:latest
    links:
      - db
    ports:
      - "5000:5000"
    networks:
      - project1
  db:
    image: mysql:latest
    command: mysql --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - project1

  analytics:
    image: stevenbennett90/3495assignment1-analytics:latest
    command: python -u calculate.py
    ports:
      - "5005:5005"
    links:
      - mongodb
      - db
    networks:
      - project1

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: test_mongodb
    command: mongod --auth
    environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: grades_db
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - project1

  result:
    container_name: result
    image: stevenbennett90/3495assignment1-result:latest
    links:
      - mongodb
    volumes:
      - ./result:/app
    ports:
      - '5002:5002'
    networks:
      - project1      

networks:
  project1:
