apiVersion: v1
kind: Pod
metadata:
  name: auth
  labels:
    name: auth
spec:
  containers:
  - name: auth
    image: stevenbennett90/3495assignment1-auth:latest
    ports:
      - containerPort: 5001
    env:
      - name: MYSQL_HOST
        value: db
      - name: MYSQL_USER
        value: root
      - name: MYSQL_PASSWORD
        value: root


---

apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    name: app
spec:
  containers:
  - name: app
    image: stevenbennett90/3495assignment1-app:latest
    ports:
      - containerPort: 5000
    env:
      - name: MYSQL_HOST
        value: db
      - name: MYSQL_USER
        value: root
      - name: MYSQL_PASSWORD
        value: root

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
    ports:
      - containerPort: 3306
        name: mysql
    volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
  volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pvc
---

apiVersion: v1
kind: Pod
metadata:
  name: analytics
  labels:
    name: analytics
spec:
  containers:
  - name: analytics
    image: stevenbennett90/3495assignment1-analytics:latest
    command:
      - python
      - "-u"
      - "calculate.py"
    ports:
      - containerPort: 5005
    env:
      - name: MONGO_DB_HOST
        value: mongodb
      - name: MYSQL_HOST
        value: db
      - name: MYSQL_USER
        value: root
      - name: MYSQL_PASSWORD
        value: root
  volumes:
  - name: analytics-volume
    emptyDir: {}


---

apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
  - name: mongodb
    image: mongo:latest
    ports:
      - containerPort: 27017
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: root
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: root
      - name: MONGO_INITDB_DATABASE
        value: grades_db
    volumeMounts:
      - name: mongodb-volume
        mountPath: /data/db
  volumes:
    - name: mongodb-volume
      emptyDir: {}

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/app

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: app
---

apiVersion: v1
kind: Pod
metadata:
  name: result
spec:
  containers:
  - name: result
    image: stevenbennett90/3495assignment1-result:latest
    volumeMounts:
    - name: app-volume
      mountPath: /app
  volumes:
  - name: app-volume
    persistentVolumeClaim:
      claimName: app-pvc


