apiVersion: v1
kind: Namespace
metadata:
  name: grades-namespace

---



apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: grades-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 3495assignment2-auth:latest

        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: grades-namespace
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 5001
    targetPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: enter-data-deployment
  namespace: grades-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enter-data
  template:
    metadata:
      labels:
        app: enter-data
    spec:
      containers:
      - name: enter-data
        image: 3495assignment2-app:latest
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: enter-data-service
  namespace: grades-namespace
spec:
  selector:
    app: enter-data
  ports:
  - name: http
    port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: grades-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: 3495assignment2-result:latest
        ports:
        - containerPort: 5002
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: grades-namespace
spec:
  selector:
    app: result
  ports:
  - name: http
    port: 5002
    targetPort: 5002

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  namespace: grades-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytics
  template:
    metadata:
      labels:
        app: analytics
    spec:
      containers:
      - name: analytics
        image: 3495assignment2-analytics:latest
        ports:
        - containerPort: 5005
      imagePullSecrets:
      - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: grades-namespace
spec:
  selector:
    app: analytics
  ports:
  - name: http
    port: 5005
    targetPort: 5005

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: grades-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:latest
        command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: grades-namespace
spec:
  selector:
    app: db
  ports:
  - name: db
    port: 3306
    targetPort: 3306
  clusterIP: None