FROM mysql:latest

# Copy the init.sql file to the container
COPY init.sql /docker-entrypoint-initdb.d/

# Set environment variables for the MySQL database
ENV MYSQL_DATABASE=grades
ENV MYSQL_ROOT_PASSWORD=root